apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: cloudbees-master
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: master-tls
  namespace: cloudbees-master
spec:
  secretName: master-tls
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: Issuer
  commonName: master.cloudbees.ddns.net
  dnsNames:
    - master.cloudbees.ddns.net