apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: lets-encrypt-prod-issuer
  namespace: nexus
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "massimo.cannavo@azblue.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nexus
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nexus-tls
  namespace: nexus
spec:
  secretName: nexus-tls
  issuerRef:
    name: lets-encrypt-prod-issuer
    kind: Issuer
  commonName: '*.nexus.ddns.net'
  dnsNames:
    - nexus.ddns.net
    - '*nexus.ddns.net'