apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus
  namespace: nexus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - policy
  resourceNames:
  - nexus
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus
  namespace: nexus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nexus
subjects:
- kind: ServiceAccount
  name: nexus-sonatype-nexus
  namespace: nexus