apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube
  namespace: sonarqube
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - policy
  resourceNames:
  - sonarqube
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube
  namespace: sonarqube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sonarqube
subjects:
- kind: ServiceAccount
  name: sonarqube
  namespace: sonarqube
- kind: ServiceAccount
  name: sonarqube-postgresql
  namespace: sonarqube